# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cadastro.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1102, 790)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1111, 761))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("nutrição.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(400, 20, 281, 71))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_2.setFont(font)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.label_nome = QtWidgets.QLabel(self.centralwidget)
        self.label_nome.setGeometry(QtCore.QRect(347, 170, 47, 13))
        self.label_nome.setObjectName("label_nome")
        self.label_idade = QtWidgets.QLabel(self.centralwidget)
        self.label_idade.setGeometry(QtCore.QRect(347, 210, 47, 13))
        self.label_idade.setObjectName("label_idade")
        self.label_sexo = QtWidgets.QLabel(self.centralwidget)
        self.label_sexo.setGeometry(QtCore.QRect(347, 250, 47, 13))
        self.label_sexo.setObjectName("label_sexo")
        self.label_altura = QtWidgets.QLabel(self.centralwidget)
        self.label_altura.setGeometry(QtCore.QRect(347, 290, 47, 13))
        self.label_altura.setObjectName("label_altura")
        self.label_peso = QtWidgets.QLabel(self.centralwidget)
        self.label_peso.setGeometry(QtCore.QRect(347, 330, 47, 13))
        self.label_peso.setObjectName("label_peso")
        self.label_objetivo = QtWidgets.QLabel(self.centralwidget)
        self.label_objetivo.setGeometry(QtCore.QRect(347, 370, 47, 13))
        self.label_objetivo.setObjectName("label_objetivo")
        self.lineEdit_nome = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_nome.setGeometry(QtCore.QRect(397, 169, 311, 21))
        self.lineEdit_nome.setObjectName("lineEdit_nome")
        self.lineEdit_idade = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_idade.setGeometry(QtCore.QRect(397, 210, 311, 21))
        self.lineEdit_idade.setObjectName("lineEdit_idade")
        self.lineEdit_sexo = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_sexo.setGeometry(QtCore.QRect(397, 249, 311, 21))
        self.lineEdit_sexo.setObjectName("lineEdit_sexo")
        self.lineEdit_altura = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_altura.setGeometry(QtCore.QRect(397, 290, 311, 21))
        self.lineEdit_altura.setObjectName("lineEdit_altura")
        self.lineEdit_peso = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_peso.setGeometry(QtCore.QRect(397, 329, 311, 21))
        self.lineEdit_peso.setObjectName("lineEdit_peso")
        self.lineEdit_objetivo = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_objetivo.setGeometry(QtCore.QRect(397, 370, 311, 111))
        self.lineEdit_objetivo.setObjectName("lineEdit_objetivo")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(490, 550, 101, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("background-color:#49d031;\n"
"color:#ffffff;\n"
"border-radius:15px;")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(470, 630, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("background-color:#49d031;\n"
"color:#ffffff;\n"
"border-radius:15px;")
        self.pushButton_6.setObjectName("pushButton_6")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.dateTimeEdit.setGeometry(QtCore.QRect(450, 500, 194, 22))
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1102, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Cadastro de Paciente e atualização"))
        self.label_nome.setText(_translate("MainWindow", "Nome: "))
        self.label_idade.setText(_translate("MainWindow", "Idade:"))
        self.label_sexo.setText(_translate("MainWindow", "Sexo:"))
        self.label_altura.setText(_translate("MainWindow", "Altura:"))
        self.label_peso.setText(_translate("MainWindow", "Peso:"))
        self.label_objetivo.setText(_translate("MainWindow", "Objetivo:"))
        self.pushButton_5.setText(_translate("MainWindow", "Salvar"))
        self.pushButton_6.setText(_translate("MainWindow", "Home"))
