# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(390, 361)
        Login.setStyleSheet("background-color:#afafaf;")
        self.frame = QtWidgets.QFrame(Login)
        self.frame.setGeometry(QtCore.QRect(50, 110, 291, 231))
        self.frame.setStyleSheet("background-color:#515151;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.lineSenha = QtWidgets.QLineEdit(self.frame)
        self.lineSenha.setGeometry(QtCore.QRect(90, 150, 113, 20))
        self.lineSenha.setStyleSheet("background-color:#ffffff;")
        self.lineSenha.setObjectName("lineSenha")
        self.lineUsuario = QtWidgets.QLineEdit(self.frame)
        self.lineUsuario.setGeometry(QtCore.QRect(90, 100, 113, 20))
        self.lineUsuario.setStyleSheet("background-color:#ffffff;")
        self.lineUsuario.setObjectName("lineUsuario")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(110, 10, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color:#ffffff;")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(110, 190, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(130, 80, 47, 13))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(130, 130, 47, 13))
        self.label_4.setObjectName("label_4")
        self.label_2 = QtWidgets.QLabel(Login)
        self.label_2.setGeometry(QtCore.QRect(140, 10, 91, 91))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../../../../Pictures/6681204.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Form"))
        self.label.setText(_translate("Login", "LOGIN"))
        self.pushButton.setText(_translate("Login", "Entrar"))
        self.label_3.setText(_translate("Login", "Usuario"))
        self.label_4.setText(_translate("Login", "Senha"))
