# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'telainicial.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1372, 877)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.cadastro = QtWidgets.QPushButton(self.centralwidget)
        self.cadastro.setGeometry(QtCore.QRect(640, 370, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.cadastro.setFont(font)
        self.cadastro.setStyleSheet("background-color:#0787ff;\n"
"color:#ffffff;\n"
"border-radius:10px;\n"
"")
        self.cadastro.setObjectName("cadastro")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1680, 980))
        self.label.setMinimumSize(QtCore.QSize(1680, 0))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../Imagens/5052425-abstrato-fundo-amarelo-e-azul-vetor.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.chamada = QtWidgets.QPushButton(self.centralwidget)
        self.chamada.setGeometry(QtCore.QRect(640, 590, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.chamada.setFont(font)
        self.chamada.setStyleSheet("background-color:#0787ff;\n"
"color:#ffffff;\n"
"border-radius:10px;\n"
"")
        self.chamada.setObjectName("chamada")
        self.relatorio = QtWidgets.QPushButton(self.centralwidget)
        self.relatorio.setGeometry(QtCore.QRect(640, 480, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.relatorio.setFont(font)
        self.relatorio.setStyleSheet("background-color:#0787ff;\n"
"color:#ffffff;\n"
"border-radius:10px;\n"
"")
        self.relatorio.setObjectName("relatorio")
        self.avaliacao = QtWidgets.QPushButton(self.centralwidget)
        self.avaliacao.setGeometry(QtCore.QRect(640, 260, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.avaliacao.setFont(font)
        self.avaliacao.setStyleSheet("background-color:#0787ff;\n"
"color:#ffffff;\n"
"border-radius:10px;\n"
"")
        self.avaliacao.setObjectName("avaliacao")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 481, 241))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../Imagens/Logo_Senac_COR.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.sair = QtWidgets.QPushButton(self.centralwidget)
        self.sair.setGeometry(QtCore.QRect(640, 730, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.sair.setFont(font)
        self.sair.setStyleSheet("background-color:#ff1e1e;\n"
"color:#ffffff;\n"
"border-radius:10px;\n"
"")
        self.sair.setObjectName("sair")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(560, 150, 701, 91))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:#ffffff;")
        self.label_3.setObjectName("label_3")
        self.label.raise_()
        self.cadastro.raise_()
        self.chamada.raise_()
        self.relatorio.raise_()
        self.avaliacao.raise_()
        self.label_2.raise_()
        self.sair.raise_()
        self.label_3.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1372, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.cadastro.setText(_translate("MainWindow", "Cadastro"))
        self.chamada.setText(_translate("MainWindow", "Lista de chamada"))
        self.relatorio.setText(_translate("MainWindow", "Relatório"))
        self.avaliacao.setText(_translate("MainWindow", "Avaliação"))
        self.sair.setText(_translate("MainWindow", "Sair"))
        self.label_3.setText(_translate("MainWindow", "SGA - Sistema de gerenciamento acadêmico "))
