# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mediaAritmetica.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(247, 271)
        MainWindow.setStyleSheet("background-color:#55aaff;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 20, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEditNum1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditNum1.setGeometry(QtCore.QRect(100, 80, 113, 20))
        self.lineEditNum1.setStyleSheet("background-color:#ffffff;")
        self.lineEditNum1.setObjectName("lineEditNum1")
        self.lineEditNum2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditNum2.setGeometry(QtCore.QRect(100, 120, 113, 20))
        self.lineEditNum2.setStyleSheet("background-color:#ffffff;")
        self.lineEditNum2.setObjectName("lineEditNum2")
        self.lineEditNum3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditNum3.setGeometry(QtCore.QRect(100, 160, 113, 20))
        self.lineEditNum3.setStyleSheet("background-color:#ffffff;")
        self.lineEditNum3.setObjectName("lineEditNum3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 80, 41, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 120, 41, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(50, 160, 41, 16))
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(90, 200, 75, 23))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 247, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Média aritmética"))
        self.label_2.setText(_translate("MainWindow", "Valor 1"))
        self.label_3.setText(_translate("MainWindow", "Valor 2"))
        self.label_4.setText(_translate("MainWindow", "Valor 3"))
        self.pushButton.setText(_translate("MainWindow", "Calcular"))
